server:
  port: 3344
spring:
  application:
    name: cloud-config-server
  cloud:
    config:
      server:
        git:
          uri: git@github.com:mario-plus/test.git
          search-paths: test  #远程仓库名
          username: 1441349884@qq.com
          password: zhouxiaoze622121
      label: master
eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://eureka7001.com:7001/eureka,http://eureka7002.com:7002/eureka
  instance:
    instance-id: cloud-config3344
    prefer-ip-address: true
