server:
  port: 6003
spring:
  application:
    name: nacos-provider-order
  cloud:
    nacos:
      discovery:
        server-addr: 127.0.0.1:8848
    sentinel:
      transport:
        port: 8719
        dashboard: 127.0.0.1:8080
#自定义变量
service-url:
  nacos-user-service: http://nacos-provider-paymnet