server:
  port: 9527
spring:
  application:
    name: cloud-gateway
  cloud:
    gateway:
      routes:
        - id: payment_route1
          #uri: http://localhost:8001
          uri: lb://cloud-payment-service
          predicates: #条件，必须为真才能访问
            - Path=/api/selectById/**,/api/timeout     #/api/selectById/**,/api/timeout
            - After=2020-03-11T10:27:28.618+08:00[Asia/Shanghai]
            #- Cookie=username, zxz
            #- Header=X-Request-Id,\d+
            #- Host=**.mario.com
            #- Method=GET
            #- Query=username,\d+
      discovery:
        locator:
          enabled: true #开启从注册中心动态创建路由功能，利用微服务名进行路由

eureka:
  client:
    #向EurekaServer服务中心注册，默认为true
    register-with-eureka: true
    #是否从EurekaServer抓取已有的注册信息，默认为true，单点无所谓，集群必须设置为true
    fetch-registry: true
    service-url:
      defaultZone: http://eureka7001.com:7001/eureka,http://eureka7002.com:7002/eureka
      #defaultZone: http://localhost:7001/eureka
  instance:
    instance-id: cloud-gateway-server9527
    prefer-ip-address: true
