server:
  port: 9999
spring:
  application:
    name: seata-gateway-comsumer
#注册进nacos
  cloud:
    gateway:
      routes:
        - id: route1
          uri: lb://seata-order-server10001
          predicates:
            - After=2020-03-11T10:27:28.618+08:00[Asia/Shanghai]

    nacos:
      discovery:
        server-addr: 127.0.0.1:8848
    sentinel:
      transport:
        port: 8719
        dashboard: 127.0.0.1:8080

management:
  endpoints:
    web:
      exposure:
        include: '*'