server:
  port: 82
eureka:
  client:
    #向EurekaServer服务中心注册，默认为true
    #register-with-eureka: true
    #是否从EurekaServer抓取已有的注册信息，默认为true，单点无所谓，集群必须设置为true
    fetch-registry: true
    service-url:
      defaultZone: http://eureka7001.com:7001/eureka,http://eureka7002.com:7002/eureka
#ribbon:
  #eureka:
    #enabled: true
spring:
  application:
    name: Feign-Payment-order82
ribbon:
  ReadTimeout: 5000
  ConnectTimeout: 5000