server:
  port: 10003
spring:
  application:
    name: seata-stock-server10003
    #nacos配置
  cloud:
    alibaba:
      seata:
        tx-service-group: fxp_tx_group     #事务组
    nacos:
      discovery:
        server-addr: 127.0.0.1:8848
    #sentinel配置
  sentinel:
    transport:
      port: 8719
      dashboard: 127.0.0.1:8080
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: org.gjt.mm.mysql.Driver
    url: jdbc:mysql://127.0.0.1:3306/seata_stock?serverTimezone=Asia/Shanghai&characterEncoding=utf8&useSSL=false
    username: root
    password: 123456
  jpa:
    hibernate:
      ddl-auto: update
management:
  endpoints:
    web:
      exposure:
        include: '*'
